[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = ["pip install -e .[web]"]

[deploy]
startCommand = "python -m web.app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
